### ISSUE TITLE
Serve requests with responses from cache when there's no backend server

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#111]
Currently, a request is blocked if there's no backend server to forward it to.

However Tempesta as a Web Server is considered a default behaviour now. If there's no backend server, requests should be served from cache. Requests should be blocked only when there's no cached response.

**Comment by krizhanovsky** [comment]
Linked with #119. We should return 404 response if there is no cache entry as well as a backend where we can fetch the entry from.

**Comment by keshonok** [comment]
This issue is implemented as described. Separate issues are opened for deeper problems that became evident after analysis of this issue. See the analysis in #119, and see new issues that refer to #119.

**Comment by keshonok** [comment]
Merged to master: 92bf359
