### ISSUE TITLE
Initiate reconnect attempts on connect error when Tempesta starts

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#112]
When Tempesta starts it initiates a connect to each backend server specified in configuration. If a connect attempt fails, then Tempesta fails to start. Observations show that a failed connect attempt may happen for multiple reasons due to nature of TCP/IP protocol and data/hardware links. It makes sense to initiate reconnect attempts when that happens on Tempesta start, and start Tempesta successfully instead of immediate failure.

**Comment by keshonok** [comment]
When running Tempesta in a virtual machine, sometimes I get error 101 (`ENETUNREACH 101 /* Network is unreachable */`)when Tempesta starts and attempts to connect to backend servers. Each time Tempesta starts fine when restarted.

**Comment by krizhanovsky** [comment]
Affects user experience significantly, so relatively crucial.

**Comment by keshonok** [comment]
Merged to master: e6eac39
