### ISSUE TITLE
Frang: RFC 7230 5.4 Host validation

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#151]
RFC 7230 5.4 says:

        A client MUST send a Host header field in all HTTP/1.1 request
        messages.  If the target URI includes an authority component, then a
        client MUST send a field-value for Host that is identical to that
        authority component, excluding any userinfo subcomponent and its "@"
        delimiter (Section 2.7.1).  If the authority component is missing or
        undefined for the target URI, then a client MUST send a Host header
        field with an empty field-value.

So Frang (```frang_http_host_check()```) must compare values of Host header with req->host and properly handle empty Host header values.

**Comment by krizhanovsky** [comment]
Also HTTP parser must support [Punycode](https://en.wikipedia.org/wiki/Punycode)

**Comment by vladtcvs** [comment]
punycode support added

**Comment by vladtcvs** [comment]
depends on #326

**Comment by vladtcvs** [comment]
fix merged
