### ISSUE TITLE
Possible double call of __ss_do_close()

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#165]
When calling `ss_close()` in Tempesta, eventually `_ss_do_close()` is called. In the process it comes to `TCP_FIN_WAIT1` socket state that is handled by `ss_tcp_state_change()` socket callback. In the callback `ss_droplink()` is called for `TCP_FIN_WAIT1` state, where `__ss_do_close()` is called as well. This leads to believe that a double call of `__ss_do_close()` may occur which is undesirable and wrong.

In practice, however, that doesn't seem to happen. Find out why.

**Comment by keshonok** [comment]
`TCP_FIN_WAIT1` state is reached only in the process of a socket close. In that process `tcp_close_state()` is called, which moves a socket from `TCP_ESTABLISHED` state to `TCP_FIN_WAIT1` state, along with sending FIN to the other end of connection. `ss_state_change()` socket callback (`sk->sk_data_ready()`) is never called in this process, so that's why there's no double call of `__ss_do_close()` in Sync Sockets.

The case for `TCP_FIN_WAIT1` state should be removed from `ss_state_change()` as unnecessary.

`sk->sk_state_change()` **is** called for `TCP_FIN_WAIT2` state though - the next state after `TCP_FIN_WAIT1`.

**Comment by krizhanovsky** [comment]
It seems we just should leave TCP_CLOSE_WAIT in the condition to be able to disassociate all resources from the socket on passive close, while we should not hook socket state change on active close. This is a bug anyway and should be fixed.

**Comment by keshonok** [comment]
Fixed in 56f0852
