### ISSUE TITLE
Repetitive HTTP 404 responses on fragmented request

### ISSUE THREAD

**Issue by i-rinat** [natsys/tempesta#195]
At version 173990895dcfc362387243f7f79cf2e6036e352a, if I make a request like that:
```
echo -en "GET / HTTP/1.1\r\nHost: loc\r\nConnection: close\r\n\r\n\r\n" | pv -L 300 | nc -q -1 192.168.122.152 80
```
with disabled cache and no backend configured, I get HTTP 404 responses one after another. Eventually they stop, when virtual machine with Tempesta runs out of memory.

There are two notable parts in the request. First, it's fragmented. Passing string through `pv -L 300` make request split in two chunk, `...loc\r\nCon` and `nection: clo...`. Second, there are additional `\r\n` at the end. Removing any of those makes reply normal.

**Comment by keshonok** [comment]
Fixed in 39ddef7
