### ISSUE TITLE
Eliminate sleeping locks in Tempesta sockets API code

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#205]
Tempesta implements its own version of sockets API functions. Some of them still use `lock_sock()` and `release_sock()` that cannot be used in SoftIRQ context as they may sleep/block. An obvious example is `ss_connect()`.

All other Tempesta sockets API functions need to be verified as well. There's a chance that some of them use sleeping/blocking locks somewhere inside the kernel. In that case those parts of the kernel code need to be brought in into `sock.c` and put inside non-blocking locks.

**Comment by keshonok** [comment]
Also, there's a bug in `ss_connect()` here: https://github.com/natsys/tempesta/blob/master/tempesta_fw/sock.c#L1031 The socket is not unlocked on return.

**Comment by krizhanovsky** [comment]
Yeah, just faced the bug:

        [sync_sockets]   ss_send: sk ffff880044ad4180, sk->sk_socket           (null), state (Established)
        [sync_sockets]   ss_send:208 entail skb=ffff88007a96d080 data_len=31 len=397
        [sync_sockets]   ss_send:226 sk=ffff880044ad4180 is_queue_empty=0 tcp_send_head(sk)=ffff88007a96d080 sk->sk_state=1
        [sync_sockets]   ss_tcp_state_change: sk ffff880044ad4180, sk->sk_socket           (null), state (Close Wait)
        [sync_sockets]   Peer connection closing
        [tempesta]   connection lost: 127.0.0.1:8080
        [tempesta]   Free msg:           (null)
        [tempesta]   Free msg: ffff880046033040
        [tempesta]   free skb ffff88007b17a200: truesize=2269 sk=          (null), destructor=          (null) users=1 type=Conn_Clnt
        [sync_sockets]   Close socket ffff880044ad4180 (account=1)
        [sync_sockets]   __ss_do_close: sk ffff880044ad4180, sk->sk_socket           (null), state (Close Wait)
        [sync_sockets]   free rcv skb ffff880044703108
        [sync_sockets]   ss_tcp_state_change: sk ffff880046033780, sk->sk_socket           (null), state (Established)
        [tempesta]   connected: 127.0.0.1:8080
        [sync_sockets]   ss_tcp_state_change: sk ffff880044ad4880, sk->sk_socket           (null), state (Close Wait)
        [sync_sockets]   Peer connection closing
        [tempesta]   connection lost: 127.0.0.1:8080
        [tempesta]   Free msg:           (null)
        BUG: scheduling while atomic: httpd/979/0x10000101
        Modules linked in: tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tfw_sched_dummy(O) tempesta_fw(O) tempesta_db(O) nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT xt_CHECKSUM iptable_mangle bridge stp llc ip6table_filter ip6_tables iptable_filter ip_tables ebtable_nat ebtables xfs exportfs ppdev microcode serio_raw i2c_piix4 i2c_core pcspkr parport_pc parport dm_mirror dm_region_hash dm_log dm_mod uinput btrfs xor zlib_deflate raid6_pq libcrc32c ata_generic pata_acpi e1000 ata_piix floppy ipv6 autofs4
        CPU: 0 PID: 979 Comm: httpd Tainted: G           O 3.10.10+ #4
        Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.8.1-20150318_183358- 04/01/2014
         ffff88007fc12d00 ffff88007fc039f0 ffffffff814cdd5f ffff88007fc03a00
         ffffffff814ca4d0 ffff88007fc03a68 ffffffff814d1618 ffff880078bd7fd8
         0000000000000246 0000000000012d00 ffff880078bd7fd8 0000000000012d00
        Call Trace:
         <IRQ>  [<ffffffff814cdd5f>] dump_stack+0x19/0x1b
         [<ffffffff814ca4d0>] __schedule_bug+0x48/0x56
         [<ffffffff814d1618>] __schedule+0x6c8/0x7c0
         [<ffffffff8106f3b6>] __cond_resched+0x26/0x30
         [<ffffffff814d1afa>] _cond_resched+0x3a/0x50
         [<ffffffff813f1a52>] lock_sock_nested+0x12/0x40
         [<ffffffffa046ba05>] lock_sock+0x1d/0x1f [tempesta_fw]
         [<ffffffffa046db95>] ss_connect+0x85/0xe8 [tempesta_fw]
         [<ffffffffa046ece5>] tfw_sock_srv_connect_try+0xb8/0xfb [tempesta_fw]
         [<ffffffffa046f06c>] tfw_sock_srv_connect_failover+0xd3/0x119 [tempesta_fw]
         [<ffffffffa046cc5f>] ss_droplink+0x80/0xa0 [tempesta_fw]
         [<ffffffffa046d509>] ss_tcp_state_change+0x20e/0x290 [tempesta_fw]
         [<ffffffff814501f9>] tcp_fin+0x169/0x1e0
         [<ffffffff81452af8>] tcp_data_queue+0x6c8/0xc90
         [<ffffffff814559af>] tcp_rcv_established+0x1bf/0x8a0
         [<ffffffff81460704>] tcp_v4_do_rcv+0x1b4/0x470
         [<ffffffff8123a2a6>] ? tempesta_sock_tcp_rcv+0x26/0x30
         [<ffffffff81461d3e>] tcp_v4_rcv+0x68e/0x7e0
         [<ffffffff8143c2c0>] ? ip_rcv_finish+0x320/0x320
