### ISSUE TITLE
Frang: handling default configuration

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#219]
```tempesta/etc/tfw_frang.conf``` says

       # Default:
       #   All limits are disabled (the values are set to zero/false/empty).

However, the empty section of ```frang_limits``` is disallowed by the system:

        # grep '^frang_limits' etc/tfw_frang.conf 
        frang_limits { }
        # ./tempesta.sh -f --start
        Loading Tempesta kernel modules...
        Load Frang
        Starting Tempesta...
        sysctl: setting key "net.tempesta.state": Invalid argument
        net.tempesta.state = start
        done
        # dmesg |tail -12
        [   39.393342] [tempesta] ERROR: the required entry is not found: 'frang_limits'
        [   39.395272] [tempesta] ERROR: configuration parsing error:
        	# Enforce sticky cookie with default name.
        #   sticky name=__cookie__ enforce;
        
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [   39.401840] [tempesta] ERROR: can't parse configuration data
        [   39.403038] [tempesta]   spec cleanup: 'listen'
        [   39.404046] [tempesta]   spec cleanup: 'server'
        [   39.405070] [tempesta]   spec cleanup: 'cache_db'
        [   39.406078] [tempesta]   spec cleanup: 'filter_db'
        [   39.407119] [tempesta] ERROR: failed to start modules

The same also for empty configuration file. This is unexpected behavior and the empty session should set default values.

**Comment by krizhanovsky** [comment]
It seems ```etc/tfw_frang.conf``` isn't read at all and ```frang_limits``` section must be defined in main configuration file, ```etc/tempesta_fw.conf```. So content of ```etc/tfw_frang.conf``` must be moved to ```etc/tempesta_fw.conf``` and the file must be removed.

**Comment by vladtcvs** [comment]
merged
