### ISSUE TITLE
Additional headers corrupts request

### ISSUE THREAD

**Issue by i-rinat** [natsys/tempesta#222]
(version a48d2a2c53fa1453cd2a275119338b1cf6ec4e1a)

While request "`GET / HTTP/1.0\r\nHost: loc\r\n\r\n`" works fine,  "`GET / HTTP/1.0\r\nHost: loc\r\nA: B\r\n\r\n`" never terminates.

Also request "`GET / HTTP/1.1\r\nConnection: close\r\nHost: loc\r\nA: B\r\nC: D\r\nE: F\r\n\r\n`" is changed so what backend gets is:
`GET Connection: close\r\n lo\nA: B\r\nC: D\r\nE: F\r\nX-Forwarded-For: 19Connection: keep-ali\r\n2.168.122.1\r\n\r\n`

**Comment by keshonok** [comment]
Fixed via cfea52b
