### ISSUE TITLE
Add compile-time assertion to build Tempesta prerequisites mismatch

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#241]
Need to check target machine for [prerequisites](https://github.com/natsys/tempesta#common):

* x86_64 architecture
* enabled SSE 4.2 and PSE flags

**Comment by sergsever** [comment]
The kernel 3.10.10+  is required.

**Comment by krizhanovsky** [comment]
Anyway there is no chance to build Tempesta w/o our kernel, so the test is unnecessary.

**Comment by sergsever** [comment]
Понял. Учту.
С уважением.
Львов Сергей.
16 Окт 2015 г. 20:38 пользователь "Alexander Krizhanovsky" <
notifications@github.com> написал:
