### ISSUE TITLE
Test build errors on release build

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#263]
$ NDEBUG=1 make
         ..........
        
        Building modules, stage 2.
        MODPOST 9 modules
        WARNING: "tfw_create_server" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_sg_release_all" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_cfg_start_mods" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_cfg_stop_mods" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_srv_conn_alloc" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_sg_add" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_cfg_mod_find" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_sg_new" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_sg_set_sched" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_hash_str" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_srv_conn_free" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!

Tests should be either be able to be built w/o DEBUG (i.e. we should migrate from DEBUG_EXPORT_SYMBOL to kallsyms hack) or not built at all w/o DEBUG. The first is prefered.

**Comment by krizhanovsky** [comment]
Now the issue appears w/o any defines for make, since now we're building Tempesta in release mode by default. Depends on #242 since tests are built also in release mode where DEBUG_EXPORT_SYMBOL is nothing.

**Comment by sergsever** [comment]
Неправильная командная строка, нужно:
make DEBUG=1
Тогда все нормально.

**Comment by krizhanovsky** [comment]
The problem still exists, but with different build option:

        # make
          Building modules, stage 2.
          MODPOST 8 modules
        WARNING: "tfw_cfg_start_mods" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_cfg_stop_mods" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_cfg_mod_find" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
        WARNING: "tfw_hash_str" [/root/tempesta/tempesta_fw/t/unit/tfw_test.ko] undefined!
          CC      /root/tempesta/tempesta_db/core/tempesta_db.mod.o

**Comment by krizhanovsky** [comment]
Fixed w/ #242 fix.
