### ISSUE TITLE
TfwStr exponential growing

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#291]
Chunks array of compound TfwStr should grow exponentially while there is no sense to grow duplicate strings exponentially and it has sense to leave the growing linear.

**Comment by krizhanovsky** [comment]
The task should be reviewed to the new TfwPool design, please see https://github.com/natsys/tempesta/commit/63295ae28c74852836cdc03f390c42eb5ab55a69 - probably  there is nothing to optimize.

**Comment by i-rinat** [comment]
Excessive reallocation issue (found in #295) was fixed in https://github.com/natsys/tempesta/pull/303.

**Comment by i-rinat** [comment]
After recent fixes, reallocation of last allocated block is a cheap operation again. Since realloc only used for growing currently processed header field, that block will always be the last. Therefore adding exponential growing will add more conditional checks, but give no benefit.
