### ISSUE TITLE
Send response on one-way closed TCP connection

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#292]
To reproduce the issue switch off ```cache``` and run backed at the same host as Tempesta. In my installation host (VM) 172.16.0.5 runs Tempesta at port 80 and Apache HTTP at port 8080.

        $ echo -en 'GET / HTTP/1.0\r\nHost: 172.16.0.5\r\nConnection: keep-alive\r\n\r\n' | nc 172.16.0.5 8080 |head
        HTTP/1.1 403 Forbidden
        Date: Sun, 04 Oct 2015 19:45:30 GMT
        Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
        Last-Modified: Thu, 16 Oct 2014 13:20:58 GMT
        ETag: "1321-5058a1e728280"
        Accept-Ranges: bytes
        Content-Length: 4897
        Keep-Alive: timeout=5, max=100
        Connection: Keep-Alive
        Content-Type: text/html; charset=UTF-8
        write: Broken pipe

The same command doesn't return page for Tempesta:

        $ echo -en 'GET / HTTP/1.0\r\nHost: 172.16.0.5\r\nConnection: keep-alive\r\n\r\n' | nc 172.16.0.5 80
        $

Tempesta log is:

        [tempesta]   GFSM move from 0x2004 to 0x5
        [tempesta]       TFW_HTTP_FSM_LOCAL_RESP_FILTER return code 0
        [sync_sockets]   ss_send: sk ffff8800457a3080, sk->sk_socket           (null), state (Established)
        [sync_sockets]   ss_send:213 entail skb=ffff880001d491c0 data_len=0 len=490
        [sync_sockets]   ss_send:231 sk=ffff8800457a3080 is_queue_empty=0 tcp_send_head(sk)=ffff880001d491c0 sk->sk_state=1
        [tempesta]       Free msg: ffff8800459a6020
        [tempesta]       free skb ffff880001d49440: truesize=2271 sk=          (null), destructor=          (null) users=1 type=Conn_Clnt
        [tempesta]       Free msg: ffff880037983020
        [tempesta]       free skb ffff880045791c48: truesize=2368 sk=          (null), destructor=          (null) users=1 type=Conn_Srv
        [sync_sockets]   ss_tcp_state_change: sk ffff88004f7f90c0, sk->sk_socket           (null), state (Close Wait)
        [sync_sockets]   received FIN, do an active close
        [sync_sockets]   Peer connection closing
        [sync_sockets]   Close socket ffff88004f7f90c0 (account=1)
        [sync_sockets]   __ss_do_close: sk ffff88004f7f90c0, sk->sk_socket           (null), state (Close Wait)

So when client sends FIN, Tempesta just drops the connection and doesn't send server response to it.

**Comment by keshonok** [comment]
After further analysis and test the consensus is that Tempesta behaves the way it's supposed to.
