### ISSUE TITLE
crash at parse_cfg_entry()

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#300]
![cfg_oops](https://cloud.githubusercontent.com/assets/884694/10335491/c8a83106-6cf9-11e5-8e41-bf1b61ef05fb.jpg)

Just a screenshot of the Oops from Zuer.

**Comment by keshonok** [comment]
This particular bug occurs when the configuration parser processes nested entries. The entry parser processes all entries starting from the opening brace '{' till the closing brace '}', and it expects that the entry to parse is valid. The entry parsing function has a `BUG_ON()` to make sure of that. However, in this case the closing brace `}` is missing, and the rest of configuration is commented out, so there are no more entries. The entry parsing function gets an invalid entry (that has 'TOKEN_NA'), and that triggers the `BUG_ON()`.

The solution is to not let the entry parser receive an invalid entry for processing. Also, in this case a more informative error message is justified about a missing closing brace.

**Comment by keshonok** [comment]
Closed via 48ce83c
