### ISSUE TITLE
tfw_http_msg_field_chunk_fixup() crash

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#328]
Just a kernel Oops so far...
![http_msg_field_chunk_fixup](https://cloud.githubusercontent.com/assets/884694/10681585/5b550bec-7933-11e5-96aa-1446a26fdd2a.jpg)

**Comment by keshonok** [comment]
This issue appears to be connected with #320, as the bug occurs at a test of whether a `TfwStr{}` string is `DUPLICATE`. It must not be a duplicate when this function is called.

I am unable to reproduce this bug so far. A possible culprit has been found and pushed to master in 356f620.

**Comment by krizhanovsky** [comment]
I double checked master branch as of Oct 23 and there is not code path leading to ```tfw_http_msg_field_chunk_fixup()``` with duplicated field.

Probably, the Oops is caused by memory corruption due to other bug. Anyway, we need HTTP message or workload description as well as full dmesg to track the issue.

**Comment by krizhanovsky** [comment]
The issues is duplicated of #320 which contains verbose description of investigation results.
