### ISSUE TITLE
[Cache] Handling requests without Host

### ISSUE THREAD

**Issue by vladtcvs** [natsys/tempesta#332]
need to send 2 requests, one with "/", next with "http://localhost/"
```
# telnet 127.0.0.1 80
GET / HTTP/1.1<enter>
<enter>
.....
GET http://localhost/ HTTP/1.1<enter>
<enter>
```
kernel faults
log with DEBUG=3 attached
[consolelog.txt](https://github.com/natsys/tempesta/files/22490/consolelog.txt)

**Comment by vladtcvs** [comment]
Update: it's a problem with cache. It disappears with cache off;

**Comment by krizhanovsky** [comment]
This is the old version of cache, before https://github.com/natsys/tempesta/commit/e983990a70bbf17b777bca69c0260247fede8bb2, which has many issues. Moreover, the problem raises at ```ss_send()``` where we also have issues on sharded cache (see #337 and #343).

So the issues is partially outdated and partially duplicate.
