### ISSUE TITLE
Memory corruption when adding/changing Connection: header in an HTTP response.

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#353]
The conditions are as follows:

- Current master branch at fad205a
- Back-end HTTP server is running on the same host with Tempesta.
- The kernel is 3.10.10, and has SLUB debugging turned on.
- Simple configuration file:
```
cache 0;
server 127.0.0.1:8080;
```
- Run the following command:
```
(echo -en "GET / HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n"; sleep 1;) | nc 127.0.0.1 80
```

The expectation is that the HTTP response contains `Connection: close` header field.

However, the response appears to corrupted. Please see the trace of two consecutive runs of the above command. Pay attention to the `Connection:` header field. On first call it's partly overwritten with the next header field. On the second response `kkkkkkk` means that the memory area has been freed.

```
[root@localhost tempesta]# (echo -en "GET / HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n"; sleep 1;) | nc 127.0.0.1 80
HTTP/1.1 403 Forbidden
Date: Fri, 13 Nov 2015 11:30:20 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
Last-Modified: Tue, 17 Jun 2014 16:00:47 GMT
ETag: "1310-4fc0a3f32a9c0"
Accept-Ranges: bytes
Content-Length: 4880
Keep-Alive: timeout=5, max=100
ConContent-Type: text/html; charset=UTF-8

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
                <title>Apache HTTP Server Test Page powered by CentOS</title>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/open-sans.css" type="text/css" />

<style type="text/css"><!--              

body {
  font-family: "Open Sans", Helvetica, sans-serif;
  font-weight: 100;
  color: #ccc;
  background: rgba(10, 24, 55, 1);
  font-size: 16px;
}

h2, h3, h4 {
  font-weight: 200;
}

h2 {
  font-size: 28px;
}

.jumbotron {
  margin-bottom: 0;
  color: #333;
  background: rgb(212,212,221); /* Old browsers */
  background: radial-gradient(ellipse at center top, rgba(255,255,255,1) 0%,rgba(174,174,183,1) 100%); /* W3C */
}

.jumbotron h1 {
  font-size: 128px;
  font-weight: 700;
  color: white;
  text-shadow: 0px 2px 0px #abc,
               0px 4px 10px rgba(0,0,0,0.15),
               0px 5px 2px rgba(0,0,0,0.1),
               0px 6px 30px rgba(0,0,0,0.1);
}

.jumbotron p {
  font-size: 28px;
  font-weight: 100;
}

.main {
   background: white;
   color: #234;
   border-top: 1px solid rgba(0,0,0,0.12);
   padding-top: 30px;
   padding-bottom: 40px;
}

.footer {
   border-top: 1px solid rgba(255,255,255,0.2);
   padding-top: 30px;
}

    --></style>
</head>
<body>
  <div class="jumbotron text-center">
    <div class="container">
          <h1>Testing 123..</h1>
                <p class="lead">This page is used to test the proper operation of the <a href="http://apache.org">Apache HTTP server</a> after it has been installed. If you can read this page it means that this site is working properly. This server is powered by <a href="http://centos.org">CentOS</a>.</p>
                </div>
  </div>
  <div class="main">
    <div class="container">
       <div class="row">
                        <div class="col-sm-6">
                        <h2>Just visiting?</h2>
                                        <p class="lead">The website you just visited is either experiencing problems or is undergoing routine maintenance.</p>
                                        <p>If you would like to let the administrators of this website know that you've seen this page instead of the page you expected, you should send them e-mail. In general, mail sent to the name "webmaster" and directed to the website's domain should reach the appropriate person.</p>
                                        <p>For example, if you experienced problems while visiting www.example.com, you should send e-mail to "webmaster@example.com".</p>
                                </div>
                                <div class="col-sm-6">
                                        <h2>Are you the Administrator?</h2>
                                        <p>You should add your website content to the directory <tt>/var/www/html/</tt>.</p>
                                        <p>To prevent this page from ever being used, follow the instructions in the file <tt>/etc/httpd/conf.d/welcome.conf</tt>.</p>

                                        <h2>Promoting Apache and CentOS</h2>
                                        <p>You are free to use the images below on Apache and CentOS Linux powered HTTP servers.  Thanks for using Apache and CentOS!</p>
                                        <p><a href="http://httpd.apache.org/"><img src="images/apache_pb.gif" alt="[ Powered by Apache ]"></a> <a href="http://www.centos.org/"><img src="images/poweredby.png" alt="[ Powered by CentOS Linux ]" height="31" width="88"></a></p>
                                </div>
                        </div>
            </div>
                </div>
        </div>
          <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">          
            <h2>Important note:</h2>
            <p class="lead">The CentOS Project has nothing to do with this website or its content,
            it just provides the software that makes the website run.</p>
            
            <p>If you have issues with the content of this site, contact the owner of the domain, not the CentOS project. 
            Unless you intended to visit CentOS.org, the CentOS Project does not have anything to do with this website,
            the content or the lack of it.</p>
            <p>For example, if this website is www.example.com, you would find the owner of the example.com domain at the following WHOIS server:</p>
            <p><a href="http://www.internic.net/whois.html">http://www.internic.net/whois.html</a></p>
          </div>
          <div class="col-sm-6">
            <h2>The CentOS Project</h2>
            <p>The CentOS Linux distribution is a stable, predictable, manageable and reproduceable platform derived from 
               the sources of Red Hat Enterprise Linux (RHEL).<p>
            
            <p>Additionally to being a popular choice for web hosting, CentOS also provides a rich platform for open source communities to build upon. For more information
               please visit the <a href="http://www.centos.org/">CentOS website</a>.</p>
          </div>
        </div>
                  </div>
    </div>
  </div>
</body></html>
[root@localhost tempesta]# 
[root@localhost tempesta]# 
[root@localhost tempesta]# (echo -en "GET / HTTP/1.1\r\nHost: 127.0.0.1\r\nConnection: close\r\n\r\n"; sleep 1;) | nc 127.0.0.1 80
HTTP/1.1 403 Forbidden
Date: Fri, 13 Nov 2015 11:32:08 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
Last-Modified: Tue, 17 Jun 2014 16:00:47 GMT
ETag: "1310-4fc0a3f32a9c0"
Accept-Ranges: bytes
Content-Length: 4880
Keep-Alive: timeout=5, max=100
Conkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"><html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
                <title>Apache HTTP Server Test Page powered by CentOS</title>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/open-sans.css" type="text/css" />

<style type="text/css"><!--              

body {
  font-family: "Open Sans", Helvetica, sans-serif;
  font-weight: 100;
  color: #ccc;
  background: rgba(10, 24, 55, 1);
  font-size: 16px;
}

h2, h3, h4 {
  font-weight: 200;
}

h2 {
  font-size: 28px;
}

.jumbotron {
  margin-bottom: 0;
  color: #333;
  background: rgb(212,212,221); /* Old browsers */
  background: radial-gradient(ellipse at center top, rgba(255,255,255,1) 0%,rgba(174,174,183,1) 100%); /* W3C */
}

.jumbotron h1 {
  font-size: 128px;
  font-weight: 700;
  color: white;
  text-shadow: 0px 2px 0px #abc,
               0px 4px 10px rgba(0,0,0,0.15),
               0px 5px 2px rgba(0,0,0,0.1),
               0px 6px 30px rgba(0,0,0,0.1);
}

.jumbotron p {
  font-size: 28px;
  font-weight: 100;
}

.main {
   background: white;
   color: #234;
   border-top: 1px solid rgba(0,0,0,0.12);
   padding-top: 30px;
   padding-bottom: 40px;
}

.footer {
   border-top: 1px solid rgba(255,255,255,0.2);
   padding-top: 30px;
}

    --></style>
</head>
<body>
  <div class="jumbotron text-center">
    <div class="container">
          <h1>Testing 123..</h1>
                <p class="lead">This page is used to test the proper operation of the <a href="http://apache.org">Apache HTTP server</a> after it has been installed. If you can read this page it means that this site is working properly. This server is powered by <a href="http://centos.org">CentOS</a>.</p>
                </div>
  </div>
  <div class="main">
    <div class="container">
       <div class="row">
                        <div class="col-sm-6">
                        <h2>Just visiting?</h2>
                                        <p class="lead">The website you just visited is either experiencing problems or is undergoing routine maintenance.</p>
                                        <p>If you would like to let the administrators of this website know that you've seen this page instead of the page you expected, you should send them e-mail. In general, mail sent to the name "webmaster" and directed to the website's domain should reach the appropriate person.</p>
                                        <p>For example, if you experienced problems while visiting www.example.com, you should send e-mail to "webmaster@example.com".</p>
                                </div>
                                <div class="col-sm-6">
                                        <h2>Are you the Administrator?</h2>
                                        <p>You should add your website content to the directory <tt>/var/www/html/</tt>.</p>
                                        <p>To prevent this page from ever being used, follow the instructions in the file <tt>/etc/httpd/conf.d/welcome.conf</tt>.</p>

                                        <h2>Promoting Apache and CentOS</h2>
                                        <p>You are free to use the images below on Apache and CentOS Linux powered HTTP servers.  Thanks for using Apache and CentOS!</p>
                                        <p><a href="http://httpd.apache.org/"><img src="images/apache_pb.gif" alt="[ Powered by Apache ]"></a> <a href="http://www.centos.org/"><img src="images/poweredby.png" alt="[ Powered by CentOS Linux ]" height="31" width="88"></a></p>
                                </div>
                        </div>
            </div>
                </div>
        </div>
          <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">          
            <h2>Important note:</h2>
            <p class="lead">The CentOS Project has nothing to do with this website or its content,
            it just provides the software that makes the website run.</p>
            
            <p>If you have issues with the content of this site, contact the owner of the domain, not the CentOS project. 
            Unless you intended to visit CentOS.org, the CentOS Project does not have anything to do with this website,
            the content or the lack of it.</p>
            <p>For example, if this website is www.example.com, you would find the owner of the example.com domain at the following WHOIS server:</p>
            <p><a href="http://www.internic.net/whois.html">http://www.internic.net/whois.html</a></p>
          </div>
          <div class="col-sm-6">
            <h2>The CentOS Project</h2>
            <p>The CentOS Linux distribution is a stable, predictable, manageable and reproduceable platform derived from 
               the sources of Red Hat Enterprise Linux (RHEL).<p>
            
            <p>Additionally to being a popular choice for web hosting, CentOS also provides a rich platform for open source communities to build upon. For more information
               please visit the <a href="http://www.centos.org/">CentOS website</a>.</p>
          </div>
        </div>
                  </div>
    </div>
  </div>
</body></html>
[root@localhost tempesta]#
```

**Comment by keshonok** [comment]
The issue is in the certain aspects of implementation of `__split_linear_data()` in `ss_skb.c`. The implementation makes an skb page fragment out of the tail of the linear data. However, that is reliable only when linear data itself is in a page, and not in kmalloc'ed memory. Otherwise, when the original skb is released, a clone of that skb is left with a pointer to released memory. Access to that memory is interpreted by the kernel as memory corruption.

The possibility of conversion of skb linear data (`skb->head`) to a page fragment is introduced with the patch by Eric Dumazet. The patch and the following discussion can be seen here: http://lists.openwall.net/netdev/2012/04/27/85.

The solution can be one of the following:
- Convert all skb that come to Tempesta to have their linear data in a page. That requires allocating a new page, inserting it as the first paged fragment of an skb, and copying data from the linear part to the paged fragment.
- Handle this case `__split_linear_data()`. Same actions are required as those described above. The difference is that it will be done only when needed, which right now is nearly always. In addition, that requires updating relevant pointers to parsed data in an skb, which may be somewhat difficult.

**Comment by krizhanovsky** [comment]
Probably faced the bug on current [master](https://github.com/natsys/tempesta/commit/aac093addc76780298675513f934a3c1129f45b5):

        BUG: unable to handle kernel paging request at ffffed008ea0feeb
        IP: [<ffffffff8103113c>] save_stack_trace+0xbc/0x100
        PGD 7ff4b067 PUD 0 
        Oops: 0000 [#1] SMP KASAN
        Modules linked in: tfw_sched_rr(O) tfw_sched_http(O) tfw_sched_hash(O) tempesta_fw(O) tempesta_db(O) nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT nf_reject_ipv4 iptable_filter ip_tables tun bridge stp llc xfs ppdev libcrc32c exportfs microcode serio_raw pcspkr parport_pc parport i2c_piix4 acpi_cpufreq i2c_core dm_mirror dm_region_hash dm_log dm_mod uinput btrfs xor raid6_pq ata_generic pata_acpi e1000 ata_piix floppy ipv6 autofs4
        CPU: 0 PID: 0 Comm: swapper/0 Tainted: G           O    4.1.12+ #43
        Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.8.1-20150318_183358- 04/01/2014
        task: ffffffff82817b20 ti: ffffffff82800000 task.ti: ffffffff82800000
        RIP: 0010:[<ffffffff8103113c>]  [<ffffffff8103113c>] save_stack_trace+0xbc/0x100
        RSP: 0018:ffff88006d007108  EFLAGS: 00010807
        RAX: dffffc0000000000 RBX: ffff88047507f75c RCX: 0000000000000001
        RDX: 1ffff1008ea0feeb RSI: 0000000000000001 RDI: ffff88006d007078
        RBP: ffff88006d007118 R08: ffff88006d007130 R09: 0000000000000000
        R10: 0000000000000001 R11: 0000000000000000 R12: 000000008100f0d4
        R13: ffffffff82817b20 R14: ffffffff81e0f5eb R15: 0000000000000000
        FS:  0000000000000000(0000) GS:ffff88006d000000(0000) knlGS:0000000000000000
        CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
        CR2: ffffed008ea0feeb CR3: 000000003b4f6000 CR4: 00000000000006f0
        Stack:
         ffff880027c2c108 ffffffff81e0f5eb ffff88006d007168 ffffffff81489a44
         ffff88006d007168 0000001000000010 ffff880027c2c110 0000000000000000
         ffffea00009f0b00 ffffea00009f0b00 ffff88004c6ec240 ffff880027c2c000
        Call Trace:
         <IRQ> 
         [<ffffffff81e0f5eb>] ? __alloc_skb+0xeb/0x600
         [<ffffffff81489a44>] set_track+0x74/0x140
         [<ffffffff8148b5a8>] alloc_debug_processing+0x178/0x180
         [<ffffffff8148d06c>] __slab_alloc+0x53c/0x560
         [<ffffffff81e0f5eb>] ? __alloc_skb+0xeb/0x600
         [<ffffffff8148d2ad>] kmem_cache_alloc_node+0x8d/0x1a0
         [<ffffffff81e0f5eb>] ? __alloc_skb+0xeb/0x600
         [<ffffffff81e0f5eb>] __alloc_skb+0xeb/0x600
         [<ffffffff81e0f500>] ? skb_scrub_packet+0x470/0x470
         [<ffffffffa0ba2570>] ? tfw_http_req_cache_cb+0x5c0/0x5c0 [tempesta_fw]
         [<ffffffffa0b9f53a>] ? __gfsm_fsm_exec+0x15a/0x2d0 [tempesta_fw]
         [<ffffffff81fba91a>] tcp_send_ack+0xfa/0x770
         [<ffffffffa0ba0c6d>] ? tfw_http_conn_msg_alloc+0x8d/0x120 [tempesta_fw]
         [<ffffffff81f61b57>] tcp_cleanup_rbuf+0x187/0x4c0
         [<ffffffffa0bd0e3e>] ss_tcp_process_data+0x77e/0xc10 [tempesta_fw]
         [<ffffffffa0bd148b>] ss_tcp_data_ready+0xfb/0x1d0 [tempesta_fw]
         [<ffffffff81f92201>] tcp_data_queue+0x10d1/0x46b0
         [<ffffffff811d8860>] ? check_irq_usage+0x190/0x190
         [<ffffffff81f91130>] ? tcp_fastretrans_alert+0x2ff0/0x2ff0
         [<ffffffff81f796a0>] ? tcp_try_coalesce+0x550/0x550
         [<ffffffff811dfac9>] ? __lock_acquire+0x1639/0x3570
         [<ffffffff811de490>] ? debug_check_no_locks_freed+0x290/0x290
         [<ffffffff81f9bff8>] tcp_rcv_established+0x798/0x2cb0
         [<ffffffff811d0020>] ? debug_mutex_add_waiter+0xa0/0x180
         [<ffffffff81f9b860>] ? tcp_validate_incoming+0xf10/0xf10
         [<ffffffff81fd2409>] tcp_v4_do_rcv+0x419/0x1570
         [<ffffffff81fd7f3b>] tcp_v4_rcv+0x26ab/0x3d50
         [<ffffffff811de490>] ? debug_check_no_locks_freed+0x290/0x290
         [<ffffffff81fd5890>] ? tcp_v4_early_demux+0x860/0x860
         [<ffffffff81efd595>] ? nf_hook_slow+0x5/0x360
         [<ffffffff81f2341b>] ip_local_deliver_finish+0x30b/0xa50
         [<ffffffff81f2328a>] ? ip_local_deliver_finish+0x17a/0xa50
         [<ffffffff81f515c1>] ? __inet_lookup_established+0x91/0x5a0
         [<ffffffff81f24252>] ip_local_deliver+0x1e2/0x220
         [<ffffffff81f24070>] ? ip_call_ra_chain+0x510/0x510
         [<ffffffff81f23110>] ? ip_rcv_finish+0x17b0/0x17b0
         [<ffffffff81f21e96>] ip_rcv_finish+0x536/0x17b0
         [<ffffffff81f24b8e>] ip_rcv+0x8fe/0x1240
         [<ffffffff81f24290>] ? ip_local_deliver+0x220/0x220
         [<ffffffff81f21960>] ? inet_del_offload+0x40/0x40
         [<ffffffff81f24290>] ? ip_local_deliver+0x220/0x220
         [<ffffffff81e4c1d1>] __netif_receive_skb_core+0x741/0x2260
         [<ffffffff81e4ba90>] ? rps_may_expire_flow+0x3c0/0x3c0
         [<ffffffff81e4dd4a>] __netif_receive_skb+0x5a/0x1a0
         [<ffffffff81e4df6e>] process_backlog+0xde/0x640
         [<ffffffff81e4e0a0>] ? process_backlog+0x210/0x640
         [<ffffffff811dfac9>] ? __lock_acquire+0x1639/0x3570
         [<ffffffff81e520d3>] net_rx_action+0x623/0xa70
         [<ffffffff811de490>] ? debug_check_no_locks_freed+0x290/0x290
         [<ffffffff81e51ab0>] ? napi_complete_done+0x1c0/0x1c0
         [<ffffffff811810c2>] ? sched_clock_tick+0x42/0xf0
         [<ffffffff810fc228>] ? __do_softirq+0x1e8/0x740
         [<ffffffff810fc285>] __do_softirq+0x245/0x740
         [<ffffffff810fcbe9>] ? __raise_softirq_irqoff+0x29/0xe0
         [<ffffffff810fca55>] irq_exit+0x175/0x1a0
         [<ffffffff81097394>] smp_call_function_single_interrupt+0x74/0x90
         [<ffffffff82174ca0>] call_function_single_interrupt+0x70/0x80
         <EOI> 
         [<ffffffff8102181b>] ? default_idle+0x5b/0x280
         [<ffffffff81021819>] ? default_idle+0x59/0x280
         [<ffffffff8102352f>] arch_cpu_idle+0xf/0x20
         [<ffffffff811c1f1f>] cpu_startup_entry+0x56f/0x760
         [<ffffffff8214bdb5>] rest_init+0x155/0x160
         [<ffffffff82bbd50a>] start_kernel+0x633/0x65b
         [<ffffffff82bbced7>] ? thread_info_cache_init+0x6/0x6
         [<ffffffff821571d9>] ? memblock_reserve+0x4c/0x51
         [<ffffffff82bbc120>] ? early_idt_handler_array+0x120/0x120
         [<ffffffff82bbc305>] x86_64_start_reservations+0x2a/0x2c
         [<ffffffff82bbc445>] x86_64_start_kernel+0x13e/0x14d
        Code: fa 48 c1 ea 03 80 3c 02 00 75 50 48 8b 43 08 41 8d 54 24 01 89 13 4a 8d 1c e0 48 b8 00 00 00 00 00 fc ff df 48 89 da 48 c1 ea 03 <80> 3c 02 00 75 20 48 c7 03 ff ff ff ff 5b 41 5c 5d c3 e8 9d 16 
        RIP  [<ffffffff8103113c>] save_stack_trace+0xbc/0x100
         RSP <ffff88006d007108>
        CR2: ffffed008ea0feeb
        ---[ end trace c357ea750c6de79a ]---
        Kernel panic - not syncing: Fatal exception in interrupt
        Kernel Offset: disabled
        ---[ end Kernel panic - not syncing: Fatal exception in interrupt
