### ISSUE TITLE
Remove "Keep-Alive:" header from responses that carry "Connection: close" header

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#377]
Tempesta sits between a client and a back-end server. It attempts to keep connections to a back-end server open for prolonged time. If a client sends `Connection: close` header in a request, Tempesta replaces it with `Connection: keep-alive` header as it passes the request to the server. When response comes, `Connection: keep-alive` header from the server is changed back to `Connection: close`. However, there's also `Keep-Alive:` header in server's response that contradicts with `Connection: close` header. For instance, it could be something like this: `Keep-Alive: timeout=5, max=100`.

`Keep-Alive:` header should be removed from responses in these cases.

Related issue: #348.

**Comment by krizhanovsky** [comment]
There is TODO comment in the code https://github.com/natsys/tempesta/blob/master/tempesta_fw/http.c#L552

**Comment by keshonok** [comment]
Implemented in 23f7c46.
