### ISSUE TITLE
Kernel panic on first run

### ISSUE THREAD

**Issue by milabs** [natsys/tempesta#449]
The following panic occurs when I've tried to run Tempesta for the first time. The only thing that I've done is to create `/opt/tempesta/tempesta.conf` while with the following content:

~~~
listen 8080;
server 127.0.0.1:80;
~~~

Then, I've run `sudo TFW_CFG_PATH=/opt/tempesta/tempesta.conf scripts/tempesta.sh --start`

![713423457_77515_5699911702071564313](https://cloud.githubusercontent.com/assets/624823/14411175/2c6b9ef8-ff49-11e5-9383-ad3714786642.jpg)

**Comment by krizhanovsky** [comment]
I'm wondering if the issue is reproducable?

**Comment by milabs** [comment]
Nope. I haven't seen that issue any more.

**Comment by krizhanovsky** [comment]
Heisenbug? :)

**Comment by milabs** [comment]
No sure. Seems that some kind of race is present.

**Comment by milabs** [comment]
Possibly fixed in 3ede3abf440453f084e1174befd0f333c4c7ad5d
