### ISSUE TITLE
The functionality to add HTTP headers to passing requests is broken

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#47]
Currently this is used in ```tfw_http_add_forwarded_for()``` to add an ```X-Forwarded-For:``` header to HTTP requests that Tempesta receives, parses, and then passes to a backend server.

One reason is the use of constructs like ```vaddr = kmap_atomic(skb_frag_page(frag));```, where something like ```frag_addr = skb_frag_address(frag);``` should be used instead. That's not the only reason for broken behaviour though.

**Comment by krizhanovsky** [comment]
```__hdr_add()``` also doesn't satisfy RFC7230 3.2.2 and generates duplicate headers.

**Comment by keshonok** [comment]
Here's an idea for a possible interface that formed in my head while I was working on sticky cookie functionality.

The base for the functionality in this issue is the ability to add/delete/replace HTTP message data that reside in an SKB. Usually HTTP message data is in a `TfwStr{}` structure that may consist of multiple data chunks. SKB data may reside in multiple data chunks as well. That is very similar to `iovec{}` structure that is used to describe data consisting of multiple chunks.

Currently Tempesta can only put linear data to an SKB starting from some offset in that SKB. (see `tfw_http_msg_setup()` and `tfw_http_msg_add_data()`). That forces us to linearize `TfwStr{}` before using this interface. It's very similar in another case of `__hdr_add()` or `__hdr_sub()` that accept linear data only, and can work only with linear areas in SKB (can't cross data chunks).

If, say, describe SKB data chunks in `TfwStr{}` terms, it would be beneficial to have an interface that allowed to copy data from one `TfwStr{}` to another `TfwStr{}`.

For instance, when we need to insert a header to HTTP message that sits in an SKB, we would find or make space in that SKB, and return a `TfwStr{}` that describes that data area. Then just copy the header using the `TfwStr{}` to `TfwStr{}` copy interface. When we need to remove a header, we already have a `TfwStr{}` that holds it. Use it as an argument to the function that does the removal. Replacement of  a header is a combination of the two above, conceptually. Again, an existing `TfwStr{}` is an argument to the function that does it.

In cases like where we need to fill out a whole SKB with an HTTP message data, an iterator would be very useful to keep current position for data copying.

I presume that there might be cases where dealing with linear data is easier. Basically, linear data is just a `TfwStr{}` that consists of a single chunk (`PLAIN`), so it's trivial to provide that interface as well on top of the above interface.
