### ISSUE TITLE
Cache: cache only specified request methods

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#494]
New configuration option `cache_meth` must be added. The option must accept space separated list of cacheable methods, e.g.

          cache_meth GET POST;

All methods, not listed in the configuration option, must not be cached. GET only must be cached by default. Tempesta must write through all non-cached methods, i.e. just proxy them w/o caching.

Please update README.md as well.

**Comment by krizhanovsky** [comment]
Cache key for POST requests also must contain request body, see [Caching POST Responses with Nginx](https://medium.com/programming-articles/caching-post-responses-with-nginx-1c0c064bb6b0) for details.

**Comment by krizhanovsky** [comment]
POST requests as well as other [non-safe](https://tools.ietf.org/html/rfc7231#section-4.2.1)/or unknown  methods must be unchacheable. Cacheable POST is a topic for #506.

**Comment by keshonok** [comment]
Implemented in b7845d2.
