### ISSUE TITLE
configuration: failure on listener address reconfiguration

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#71]
etc/tempesta_fw.conf says that the default ```listen``` value is ```listen 80``` and that ```If only PORT is given, then the address 0.0.0.0 (but not [::1]) is used.```. However, this isn't true: if I start Tempesta with default config, then I see 

        tcp        0      0 127.0.0.1:80            0.0.0.0:*               LISTEN      -                   

in netstat output.

Now I set ```listen 80;``` explicitly and execute ```./tempesta.sh restart```:

         [root@localhost tempesta]# ./tempesta.sh restart
         Stopping Tempesta...
         net.tempesta.state = stop
         Starting Tempesta...
         sysctl: setting key "net.tempesta.state": Invalid argument
         net.tempesta.state = start
         done
         done

Dmesg log:

        [ 9319.871284] [tdb] Start Tempesta DB
        [ 9319.880333] [tempesta] Initializing Tempesta FW kernel module...
        [ 9319.880794] [tempesta] init: cfg_if
        [ 9319.881029] [tempesta] init: http
        [ 9319.881221] [tempesta] init: server
        [ 9319.881437] [tempesta] init: client
        [ 9319.881657] [tempesta] init: session
        [ 9319.881878] [tempesta] init: connection
        [ 9319.882151] [tempesta]   register cfg: cache
        [ 9319.882458] [tempesta]   register cfg: sock_backend
        [ 9319.882787] [tempesta]   register cfg: sock_frontend
        [ 9319.884608] [tempesta] Registering new scheduler: dummy
        [ 9319.886167] [tempesta] got state via sysctl: start
        [ 9319.886855] [tempesta]   reading configuration file...
        [ 9319.887363] [tempesta]   reading file: /root/tempesta/etc/tempesta_fw.conf
        [ 9319.888033] [tempesta]   file size: 2204 bytes
        [ 9319.888459] [tempesta]   read by offset: 0
        [ 9319.888873] [tempesta]   read by offset: 2204
        [ 9319.889297] [tempesta] starting all modules...
        [ 9319.889720] [tempesta]   parsing configuration and pushing it to modules...
        [ 9319.890391] [tempesta]   use default entry: 'cache off;'
        [ 9319.890897] [tempesta]   spec handle: 'cache'
        [ 9319.891322] [tempesta]   use default entry: 'cache_size 262144;'
        [ 9319.891883] [tempesta]   spec handle: 'cache_size'
        [ 9319.892349] [tempesta]   use default entry: 'cache_dir /opt/tempesta/cache;'
        [ 9319.893015] [tempesta]   spec handle: 'cache_dir'
        [ 9319.893457] [tempesta]   use default entry: 'backend 127.0.0.1:8080;'
        [ 9319.894108] [tempesta]   spec handle: 'backend'
        [ 9319.894543] [tempesta]   use default entry: 'listen 127.0.0.1:80;'
        [ 9319.895130] [tempesta]   spec handle: 'listen'
        [ 9319.895571] [tempesta]   created front-end socket: sk=ffff880030dfd7c0
        [ 9319.896536] [tempesta]   starting modules...
        [ 9319.896954] [tempesta]   mod_start(): cache
        [ 9319.897367] [tempesta]   mod_start(): sock_backend
        [ 9319.897858] [tempesta]   Starting thread: tfw_bconnd
        [ 9319.898362] [tempesta]   mod_start(): sock_frontend
        [ 9319.898829] [tempesta]   start listening on socket: sk=ffff880030dfd7c0
        [ 9319.899466] [tempesta] modules are started
        [ 9340.766809] [tempesta] got state via sysctl: stop
        [ 9340.767376] [tempesta] stopping all modules...
        [ 9340.767847] [tempesta]   stopping modules...
        [ 9340.768268] [tempesta]   mod_stop(): sock_frontend
        [ 9340.768719] [tempesta]   release front-end socket: sk=ffff880030dfd7c0
        [ 9340.769348] [tempesta]   mod_stop(): sock_backend
        [ 9340.769792] [tempesta]   Stopping thread: tfw_bconnd
        [ 9340.770334] [tempesta] tfw_bconnd: stopping
        [ 9340.770764] [tempesta]   spec cleanup: 'backend'
        [ 9340.771230] [tempesta]   mod_stop(): cache
        [ 9340.771624] [tempesta]   spec cleanup: 'cache_dir'
        [ 9340.773728] [tempesta] Un-registering scheduler: dummy
        [ 9340.775833] [tempesta] exiting...
        [ 9340.776244] [tempesta]   stopping and unregistering all cfg modules
        [ 9340.776830] [tempesta]   unregister cfg: sock_frontend
        [ 9340.777331] [tempesta]   unregister cfg: sock_backend
        [ 9340.777807] [tempesta]   unregister cfg: cache
        [ 9340.779368] [tdb] Shutdown Tempesta DB
        [ 9651.546177] [tdb] Start Tempesta DB
        [ 9651.556668] [tempesta] Initializing Tempesta FW kernel module...
        [ 9651.557322] [tempesta] init: cfg_if
        [ 9651.557682] [tempesta] init: http
        [ 9651.558019] [tempesta] init: server
        [ 9651.558376] [tempesta] init: client
        [ 9651.558726] [tempesta] init: session
        [ 9651.559094] [tempesta] init: connection
        [ 9651.559482] [tempesta]   register cfg: cache
        [ 9651.559890] [tempesta]   register cfg: sock_backend
        [ 9651.560376] [tempesta]   register cfg: sock_frontend
        [ 9651.562353] [tempesta] Registering new scheduler: dummy
        [ 9651.564137] [tempesta] got state via sysctl: start
        [ 9651.564706] [tempesta]   reading configuration file...
        [ 9651.565210] [tempesta]   reading file: /root/tempesta/etc/tempesta_fw.conf
        [ 9651.565859] [tempesta]   file size: 2204 bytes
        [ 9651.566314] [tempesta]   read by offset: 0
        [ 9651.566717] [tempesta]   read by offset: 2204
        [ 9651.567147] [tempesta] starting all modules...
        [ 9651.568507] [tempesta]   parsing configuration and pushing it to modules...
        [ 9651.569268] [tempesta]   use default entry: 'cache off;'
        [ 9651.569779] [tempesta]   spec handle: 'cache'
        [ 9651.570212] [tempesta]   use default entry: 'cache_size 262144;'
        [ 9651.570779] [tempesta]   spec handle: 'cache_size'
        [ 9651.571248] [tempesta]   use default entry: 'cache_dir /opt/tempesta/cache;'
        [ 9651.571905] [tempesta]   spec handle: 'cache_dir'
        [ 9651.572366] [tempesta]   use default entry: 'backend 127.0.0.1:8080;'
        [ 9651.572967] [tempesta]   spec handle: 'backend'
        [ 9651.573418] [tempesta]   use default entry: 'listen 127.0.0.1:80;'
        [ 9651.573993] [tempesta]   spec handle: 'listen'
        [ 9651.574481] [tempesta]   created front-end socket: sk=ffff880024091800
        [ 9651.575104] [tempesta]   starting modules...
        [ 9651.575517] [tempesta]   mod_start(): cache
        [ 9651.575916] [tempesta]   mod_start(): sock_backend
        [ 9651.576388] [tempesta]   Starting thread: tfw_bconnd
        [ 9651.576900] [tempesta]   mod_start(): sock_frontend
        [ 9651.577389] [tempesta]   start listening on socket: sk=ffff880024091800
        [ 9651.578021] [tempesta] modules are started
        [ 9652.578236] [tempesta] Connected to backend: 127.0.0.1:8080
        [ 9704.000739] [sync_socket]   Close socket ffff8800313da840 (account=1)
        [ 9704.001850] [tempesta]   Close socket ffff8800313da840, conn=ffff8800333f0438
        [ 9704.002728] [tempesta]   Free msg:           (null)
        [ 9704.003051] [tempesta]   Free connection: ffff8800333f0438
        [ 9704.003681] [sync_socket]   free rcv skb ffff880024080e88
        [ 9883.037803] [tempesta] got state via sysctl: stop
        [ 9883.038370] [tempesta] stopping all modules...
        [ 9883.038869] [tempesta]   stopping modules...
        [ 9883.039304] [tempesta]   mod_stop(): sock_frontend
        [ 9883.039808] [tempesta]   release front-end socket: sk=ffff880024091800
        [ 9883.040452] [tempesta]   mod_stop(): sock_backend
        [ 9883.040902] [tempesta]   Stopping thread: tfw_bconnd
        [ 9883.041342] [tempesta] tfw_bconnd: stopping
        [ 9883.041835] ------------[ cut here ]------------
        [ 9883.042257] kernel BUG at /root/tempesta/tempesta_fw/server.c:39!
        [ 9883.042332] invalid opcode: 0000 [#1] SMP
        [ 9883.042332] Modules linked in: tfw_sched_dummy(O) tempesta_fw(O) tempesta_db(O) sync_socket(O) nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT xt_CHECKSUM iptable_mangle bridge stp llc ip6table_filter ip6_tables iptable_filter ip_tables ebtable_nat ebtables xfs exportfs ppdev parport_pc microcode serio_raw parport pcspkr i2c_piix4 i2c_core dm_mirror dm_region_hash dm_log dm_mod uinput btrfs xor zlib_deflate raid6_pq libcrc32c ata_generic pata_acpi e1000 ata_piix floppy ipv6 autofs4 [last unloaded: sync_socket]
        [ 9883.042332] CPU: 0 PID: 10966 Comm: tfw_bconnd Tainted: G           O 3.10.10+ #29
        [ 9883.042332] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.7.5-0-ge51488c-20140602_164612-nilsson.home.kraxel.org 04/01/2014
        [ 9883.042332] task: ffff88007aef17f0 ti: ffff880024f18000 task.ti: ffff880024f18000
        [ 9883.042332] RIP: 0010:[<ffffffffa0512ab8>]  [<ffffffffa0512ab8>] tfw_destroy_server+0x30/0xdf [tempesta_fw]
        [ 9883.042332] RSP: 0018:ffff880024f19d48  EFLAGS: 00010202
        [ 9883.042332] RAX: 0000000000000001 RBX: ffff8800313da840 RCX: 0000000000000020
        [ 9883.042332] RDX: ffffffffffffffe0 RSI: ffffffffffffffff RDI: ffff8800313da840
        [ 9883.042332] RBP: ffff880024f19d60 R08: 0000000000000000 R09: 0000000000000219
        [ 9883.042332] R10: 0000000000000050 R11: 0000000000000002 R12: ffff8800313da9c0
        [ 9883.042332] R13: 0000000000000007 R14: ffff8800313da8b0 R15: 0000000000000000
        [ 9883.042332] FS:  0000000000000000(0000) GS:ffff88007fc00000(0000) knlGS:0000000000000000
        [ 9883.042332] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
        [ 9883.042332] CR2: 00007fabf8587320 CR3: 0000000024056000 CR4: 00000000000006f0
        [ 9883.042332] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
        [ 9883.042332] DR3: 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400
        [ 9883.042332] Stack:
        [ 9883.042332]  ffff8800313da840 0000000000000000 ffff880024f19d80 ffff880024f19d88
        [ 9883.042332]  ffffffff813f0f8f ffff8800313da840 ffff8800313da9c0 0000000000000007
        [ 9883.042332]  ffff880024f19d98 ffffffff813f1101 ffff880024f19dc8 ffffffff814492a1
        [ 9883.042332] Call Trace:
        [ 9883.042332]  [<ffffffff813f0f8f>] __sk_free+0x1f/0x170
        [ 9883.042332]  [<ffffffff813f1101>] sk_free+0x21/0x30
        [ 9883.042332]  [<ffffffff814492a1>] tcp_close+0x141/0x3f0
        [ 9883.042332]  [<ffffffffa05134a4>] ? release_backend_socks+0x60/0x60 [tempesta_fw]
        [ 9883.042332]  [<ffffffff81470c57>] inet_release+0x77/0x80
        [ 9883.042332]  [<ffffffff813eb81f>] sock_release+0x1f/0x80
        [ 9883.042332]  [<ffffffffa0513483>] release_backend_socks+0x3f/0x60 [tempesta_fw]
        [ 9883.042332]  [<ffffffffa05136b9>] tfw_bconnd+0x215/0x21c [tempesta_fw]
        [ 9883.042332]  [<ffffffff81061020>] ? wake_up_bit+0x30/0x30
        [ 9883.042332]  [<ffffffff81060350>] kthread+0xc0/0xd0
        [ 9883.042332]  [<ffffffff81060290>] ? insert_kthread_work+0x40/0x40
        [ 9883.042332]  [<ffffffff814d939c>] ret_from_fork+0x7c/0xb0
        [ 9883.042332]  [<ffffffff81060290>] ? insert_kthread_work+0x40/0x40
        [ 9883.042332] Code: 55 48 89 e5 48 83 ec 18 48 89 7d e8 48 8b 45 e8 48 8b 80 20 02 00 00 48 89 45 f0 48 83 7d f0 00 0f 94 c0 0f b6 c0 48 85 c0 74 02 <0f> 0b 48 8b 45 f0 48 8b 40 18 48 89 45 f8 48 83 7d f8 00 0f 94
        [ 9883.042332] RIP  [<ffffffffa0512ab8>] tfw_destroy_server+0x30/0xdf [tempesta_fw]
        [ 9883.042332]  RSP <ffff880024f19d48>
        [ 9883.072752] ---[ end trace 1c7611e0e034c871 ]---
        [ 9883.073572] [tempesta]   spec cleanup: 'backend'
        [ 9883.074283] [tempesta]   mod_stop(): cache
        [ 9883.075035] [tempesta]   spec cleanup: 'cache_dir'
        [ 9883.077420] [tempesta] got state via sysctl: start
        [ 9883.078193] [tempesta]   reading configuration file...
        [ 9883.079141] [tempesta]   reading file: /root/tempesta/etc/tempesta_fw.conf
        [ 9883.079850] [tempesta]   file size: 2215 bytes
        [ 9883.080341] [tempesta]   read by offset: 0
        [ 9883.080875] [tempesta]   read by offset: 2215
        [ 9883.081325] [tempesta] starting all modules...
        [ 9883.081817] [tempesta]   parsing configuration and pushing it to modules...
        [ 9883.082494] [tempesta]   spec handle: 'listen'
        [ 9883.083073] [tempesta] ERROR: Can't parse IP address: '80'
        [ 9883.083696] [tempesta] ERROR: can't parse IP address: '80'
        [ 9883.084272] [tempesta] ERROR: configuration handler returned error: -22
        [ 9883.084992] [tempesta] ERROR: configuration parsing error:
 
        #   cache_size 1048576; # 1 GiB
        #
        # Default:
        #   cache_size 262144;  # 256 MiB
 
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        [ 9883.087344] [tempesta] ERROR: can't parse configuration data
        [ 9883.087953] [tempesta] ERROR: failed to start modules

**Comment by vdmit11** [comment]
fixed in: b7240b350c7d7663e38cfcf5f685a13ce9952b83
pull request: #57
