### ISSUE TITLE
http_parser: bad handling of fragmented HTTP messages

### ISSUE THREAD

**Issue by vdmit11** [natsys/tempesta#72]
Scenario:
1. `git checkout http-parser-frag`
2. `make test`

Result: a failed test, e.g.:
```
[   35.639269] tfw_test: EXPECT_TFWSTR_EQ(h_connection, s_connection) => false
[   35.639971] tfw_test: expected: 'Connection: Keep-Alive'
[   35.640542] tfw_test: got chunk: len=13, data='Connection: K'
[   35.641125] tfw_test: got chunk: len=10, data='eep-Alive
'
[   35.641683] tfw_test: /home/wq/natsys-lab/tempesta/tempesta_fw/t/unit/test_http_parser.c:277: error: 
[   35.642620] tfw_test: FAIL:
[   35.642920] tfw_test:   test__http_parser__fills_hdr_tbl()
[   35.643476] tfw_test:   these strings (see above) do not match
```

It fails because there is an extra `\r` character in the second chunk of the parsed header. The `len` should be 9, but it is actually 10.

The error is caused by this code:
https://github.com/natsys/tempesta/blob/http-parser-frag/tempesta_fw/http_parser.c#L849
```
		TRY_STR_LAMBDA("keep-alive", {
			if (msg->flags & TFW_HTTP_CONN_CLOSE)
				return CSTR_NEQ;
			msg->flags |= TFW_HTTP_CONN_KA;
			__FSM_I_MOVE_str(I_EoT, "keep-alive");
		});
```

Basically it is executed in the following scenario:
0. The header line is split into two chunks: "Connection: K" and "eep-Alive\r\n".
1. The parser FSM reads "Connection: " and the control reaches the `TRY_STR_LAMBDA()` at the position of "K".
2. `TRY_STR_LAMBDA()` reads `K`, but that is not enough, so it returns `CSTR_POSTPONE` and the FSM exits.
3. The next chunk is passed to the FSM, and `TRY_STR_LAMBDA()` reads "eep-alive". The string matches and it executes the code passed to the macro.
4. The `__FSM_I_MOVE_str()` moves the FSM to 10 steps forward from the current position, but not from a position where the `TRY_STR_LAMBDA()` was executed before. The position is changed since then, now it is the start of the second chunk ("eep-alive\r\n"), hence the extra "\r" character is added to the header.

The issue is not just about this particular header. It is about the whole parser. The `TRY_STR()/TRY_STR_LAMBDA()` is almost always used in this buggy way. This approach should be revised and fixed.

Beside the `TRY_STR_LAMBDA()`, there likely are other problems with the fragmentation exist in the parser, but now tests can't detect them. They will appear in future after the fix.

**Comment by krizhanovsky** [comment]
Scan alphabets like uap_a or xff_a have less than 8 ranges, so they can be replaced by SSE 4.2 CMPESTRI for large contiguous data for performance improvement.
