### ISSUE TITLE
lb: improve design of load balancing interfaces

### ISSUE THREAD

**Issue by vdmit11** [natsys/tempesta#78]
**1.  `TfwScheduler`**

The interface is currently defined as follows:

```
typedef struct {
	const char *name;
	TfwServer *	(*get_srv)(TfwMsg *msg);
	int		(*add_srv)(TfwServer *srv);
	int		(*del_srv)(TfwServer *srv);
} TfwScheduler;
```

And it has two problems with the interface:

1. It is stateful. Therefore:
    - All schedulers have to maintain the global list of all servers, and the implementation is pretty much same in every scheduler. Tempesta FW maintains its own list of servers (to manage connections to backend servers). All operations on these lists should be synchronized which is tricky, because you have to update two lists atomically (otherwise a scheduler may return a server which is offline).
    - Multiple schedulers cannot be used simultaneously, and a single scheduler cannot be used with multiple group of servers. There has to be one scheduler and one global list of servers.

2. There is no failovering interface:
    - A scheduler manages only online servers. When the server goes offline, it is deleted from the scheduler until a connection is re-established. That is done by `add_srv()`/`del_srv()` that delete an element from the global list of servers (implemented in every scheduler). The deletion should be synchronized with reads, hence there is extra locking/RCU protection in every scheduler. That has some overhead and makes the code more complex. It would be better to just mark a server offline instead of deleting it via `del_srv()`.
    - The `get_srv()` returns a `TfwServer`, but we can have multiple parallel connections to the same server. A particular connection is chosen by round-robin/hash, so there is duplicate logic in scheduler modules and Tempesta FW.
    - There is two levels of failovering: we have to switch between online/offline servers, but also we have to switch over open/closed connections within a server. The implementation turns out to be complex because it is spread across several units/modules.
    - When a server goes offline, it is deleted from the scheduler via `del_srv()`. The `del_srv()` usually uses RCU to protect the deletion. Therefore, there is a relatively long period of time (an interval between grace periods) when a scheduler may return an offline server.

I suggest the new set of interfaces for the schedulers:

```
typedef struct TfwLbGroup TfwLbGroup;
typedef struct TfwLbSched TfwLbSched;
typedef struct TfwLbSrv TfwLbSrv;

/**
 * A backend server representation containing a set of parallel connections.
 * It corresponds to one "backend" entry in the configuration file.
 */
struct TfwLbSrv {
	/* The @srv is the "superclass" field. It is exported to Tempesta FW.
	 * other fields are private to the load balancing code. */
	TfwServer srv;

	/* The pool of parallel connections. Schedulers may access it. */
	struct socket socks[];
	size_t        socks_n;
};

/**
 * A group of TfwLbSrv objects. A bunch of "backend" entries can be grouped
 * together to a "backend_group" in the configuration file, so this structure
 * corresponds to the "backend_group".
 *
 * Schedulers made stateless. They don't maintain a list of servers anymore.
 * Instead, the list of servers is stored in the TfwLbGroup and managed by
 * the Tempesta FW (it has to do it anyway because it connects to servers).
 *
 * All writes to the TfwLbGroup are done via RCU, so schedulers can safely
 * assume that the data is immutable and don't do any locking or implement
 * complicated lock-free algorithms.
 */
struct TfwLbGroup {
	/* The list of servers belonging to the group. */
	TfwLbSrv         srvs[];

	/* The scheduling algorithm that chooses a server/connection.
	 * @sched_data contains some private implementation-specific data:
	 * round-robin counters, hashes, weights, etc. */
	TfwLbSched       *sched;
	void             *sched_data;
};

/**
 * The impotant point is the TfwLbGroup and TfwLbSrv objects are managed
 * by the Tempesta FW, but not the scheduler. A scheduler module is not allowed
 * to modify these structures. A scheduler is only allowed to write @sched_data.
 *
 * Functions in this structure are hooks rather than methods. These hooks allow
 * the scheduler to receive events: when a group or server is created/deleted,
 * or when a connection is established or closed.
 */
struct TfwLbSched {
	/* These hooks are invoked called Tempesta FW creates/deletes a TwLbGroup.
	 * The scheduler can allocate/free @sched_data there. */
	int  create_group(TfwLbGroup *group);
	void delete_grpup(TfwLbGroup *group);

	/* These hooks are called when a TfwLb is added/deleted to/from a TfwLbGroup
	 * to let the scheduler update its @sched_data accordingly. */
	int add_srv(TfwLbGroup *group, TfwLbSrv *srv);
	int del_srv(TfwLbGroup *group, TfwLbSrv *srv);

	/* The hook is called when the Tempesta FW detects and re-establishes
	 * the closed connection. The scheduler must update @sched_data.
	 *
	 * The replace() is used instead of a add()/del() pair because it is
	 * much easier to implement: Tempesta FW should protect any update of
	 * TfwLbGroup with RCU (hence the replace()), so the scheduler doesn't
	 * need to synchronize with get_conn() and implement complicated
	 * lock-free structures. All it has to do is to replace a pointer. */
	int replace_conn(TfwLbGroup *group, TfwLbSrv *srv,
			 struct socket *old, struct socket *new);

	/* The only "non-hook" function that implements the actual scheduling
	 * algorithm (chooses a server/connection from the group). */
	int get_conn(TfwLbGroup *group, TfwServer **out_srv, struct sock **out_sk);
};
```

The main points are:

1. Schedulers made more stateless. Now they don't have to maintain the global list of servers. Schedulers now use (but don't create or delete) `TfwLbGroup`/`TfwLbSrv` objects managed by tempesta. The Tempesta FW had to maintain the global state anyway to manage backend connections and configuration, so now we have just one global state instead of two, hence many synchronization problems go away.

2. Multiple scheduler modules may be loaded at the same time, and each `TfwLbGroup` may choose its own scheduler. In the configuration file it looks like:
```
backend_group sched=hash {
         backend 10.0.0.1;
         backend 10.0.0.2;
         backend 10.0.0.3;
         ...
}
```

3. Scheduler modules now are aware of sockets. They listen for connect/disconnect events and implement some failovering logic. That may seem awkward and bloated, but actually that makes the implementation much simpler. There is a [prototype implementation in the `failover` branch](https://github.com/natsys/tempesta/blob/failover/tempesta_fw/lb/tfw_lb_http.c#L137), and a scheduler implementation fits to the 100 lines of code or so. Without sockets, the implementation would consist of much more code across different modules/units. As a bonus, the prototype implementation always returns an alive socket if there is at least one alive connection in a group. That makes failover switching trivial.

**2.  `tfw_sched_http`**

The problems with the scheduler are:

1. It requires backend groups, while the Tempesta FW doesn't implement them. The scheduler  already implements a kind of `TfwLbSrv`/`TfwLbGroup` objects, see [`TfwSchedHttpCfgBeGroup`/`TfwBeGroupAddrSet`/`TfwRrPtrSet`](https://github.com/natsys/tempesta/blob/master/tempesta_fw/sched/tfw_sched_http.c#L116). That leads to duplicate logic again: the Tempesta FW implements the global list of servers, and the `tfw_sched_http` implements the list of servers (and also groups servers together).

2. Backend connections are managed by Tempesta FW, but groups of servers are managed by the `tfw_sched_http`. Hence, a system administrator has to duplicate each `backend` entry in the configuration file when he uses the `tfw_sched_http` (see [tfw_sched_http.conf](https://github.com/natsys/tempesta/blob/master/etc/tfw_sched_http.conf)).

3. The `tfw_sched_http` uses the round-robin approach to pick a server from a group, so again, we have the same logic as in `tfw_sched_rr`.

It seems the `tfw_sched_http` should not be a scheduler. Usually schedulers are much more generic, they deal with resources, collections, queues, weights, etc. The `tfw_sched_http` routes HTTP requests based on a static set of `URI`/`Host` values. That seems more like a request dispatcher than a scheduler.

I suggest to move the `tfw_sched_http` to a separate entity, I will call it "dispatcher". The dispatcher's responsibility is to choose a `TfwLbGroup` for the HTTP request, while the scheduler's responsibility is to choose a particular server within the group.

There is a [prototype implementation in the `failover` branch](https://github.com/natsys/tempesta/blob/failover/tempesta_fw/lb/tfw_lb_http.c#L237).

The whole `tfw_sched_http`'s job is done by the single function in the prototype implementation, but that will change: the #76 imples large amounts of sites proxied by the Tempesta FW, so the dispatcher presumably will implement some efficient search algorithms (search trees, hash tables, etc). From this point of view, the separate dispatcher concept is even more benefitcial: the dispatcher will work with the large set of groups, and the scheduler will select a server from the small group, hence different optimization techniques may be used.

**Comment by krizhanovsky** [comment]
```connection.c``` has following comment for ```tfw_connection_recv()```:

        /**
         * TODO/FIXME
         * Things which happen in the function are wrong. We have to choose backend
         * server when the request is [fully?] parsed to be able to route static and
         * dynamic requests to different server (so we need to know at least base part
         * of URI to choose a server).
         *
         * Probably, following scheme is most suitable:
         * 1. schedulers which are going to route request depending on URI must register
         *    hook TFW_HTTP_HOOK_REQ_STATUS and adjust server information;
         * 2. schedulers which schedule request depending on server stress on
         *    round-robin actully should do their work as early as possible to reduce
         *    message latency and accelerator memory consumption (that parts of
         *    the request can be sent to server immediately) and choose the server
         *    in this function.
         *
         * So at least we need scheduler interface which can register its callbacks in
         * different places.
         */

, which also must be fixed.

**Comment by vdmit11** [comment]
> should do their work as early as possible
> parts of the request can be sent to server immediately
That may not be beneficial in some cases: during a DoS attack, the most of incoming HTTP requests are malicious. Such requests are dropped at certain stages of parsing, but before that happens, we send some data to backend servers and do the scheduling job. That is waste of resources, especially for the backend server.

**Comment by krizhanovsky** [comment]
Currently ```TfwServer``` refers to only one server socket ```sock``` while ```TfwConnection``` refers to the server, but doesn't to the socket. This is wrong and ```tfw_create_server()``` accepts ```TfwConnection``` at the same time as the socket pointer.

Failover schedulers should work with many ```TfwConnection```'s per server, so ```TfwServer``` must refer to set of ```TfwConnection```s and ```TfwConnection``` should refer to socket.

**Comment by krizhanovsky** [comment]
@vdmit11 ,

> All schedulers have to maintain the global list of all servers, and the implementation is pretty much same in every scheduler. Tempesta FW maintains its own list of servers (to manage connections to backend servers). All operations on these lists should be synchronized which is tricky, because you have to update two lists atomically (otherwise a scheduler may return a server which is offline).

All the points about duplicate logic to handle two lists are senseless. Global server list is required for any proxy mode, while shceduler list is pure reverse proxy thing. Also there is no surprise that Linux itself also handles list of sockets, so we actually have 3 lists.

> Multiple schedulers cannot be used simultaneously, and a single scheduler cannot be used with multiple group of servers. There has to be one scheduler and one global list of servers.

Yeah, good thing to have.

> A scheduler manages only online servers. When the server goes offline, it is deleted from the scheduler until a connection is re-established.....

Ok, ```offline_srv()``` and ```online_srv()``` callbacks will be introduced to mark/unmark a server as offline/online.

> The get_srv() returns a TfwServer, but we can have multiple parallel connections to the same server....

Actually, now ```tfw_sched_get_srv_conn()```, then entry point for the scheduler, returns a connection now. I'll rework ```get_srv()``` callback that it will return ```TfwConnection``` and a scheduler can operate on connections level, rather than on server level.

> There is two levels of failovering....

Yes, and this is the right way to go. Low-level connection failovering is happen in ```sock_srv.c``` while high-level server failovering is happen in particular scheduler module.

> Scheduler modules now are aware of sockets. They listen for connect/disconnect events and implement some failovering logic. That may seem awkward and bloated, but actually that makes the implementation much simpler. There is a [prototype implementation in the failover branch](https://github.com/natsys/tempesta/blob/failover/tempesta_fw/lb/tfw_lb_http.c#L137),...

This is bad since you move low level functionality to high-level module. I've commented in the pull request that scheduler modules should not do connection logic.

> ..... there is a relatively long period of time (an interval between grace periods) when a scheduler may return an offline server.

Not. New readers should not find already deleted item. However, current readers can work with the item relatively long.

> ...a system administrator has to duplicate each backend entry in the configuration file when he uses the tfw_sched_http (see tfw_sched_http.conf)

That's bad. It looks like poor implementation of configuration handling. Why do we need to specify servers list twice? Configuration should have nothing with internal scheduling design.

> The tfw_sched_http uses the round-robin approach to pick a server from a group, so again, we have the same logic as in tfw_sched_rr

Well, both the schedulers schedule requests. So do we have duplicate logic? This is just an occasion that two algorithms do something similar things. If one of them is just a superset of other one, then it's Ok to merge them to single module. You already did it in ```failover``` branch and this is again just an implementation details - there is nothing about general scheduling infrastructure.

**Comment by vdmit11** [comment]
> Yes, and this is the right way to go. Low-level connection failovering is happen in sock_srv.c while high-level server failovering is happen in particular scheduler module.
> This is bad since you move low level functionality to high-level module. I've commented in the pull request that scheduler modules should not do connection logic.

The prototype `failover` implementation proposes two "features":
 1. `sched_rr` "sends" a request to each connection of the same server before switching to another server. If you move connections out of the scheduler, then you send one request to each server, and only then switch to a new connection of the same server. In other words, the `sched_rr` is able to make "bursts" of N requests to the same server, where N is the number of connections.
 2. `sched_http` uses the hash value to choose a connection. That means that you can route requets with the same URI/Host not just to the same server, but also to the same connection within the server.

If you don't need this, then ok, we can separate the scheduling and failovering logic.

> Not. New readers should not find already deleted item. However, current readers can work with the item relatively long.

Not a deleted item, but an offline server. An offline server is deleted via RCU, so readers may get an offline server which is not yet deleted. Schedulers don't know whether a server is offline or it is completely deleted from the Tempesta FW. The proposed `offline_srv()`/`online_srv()` can solve the issue.

> That's bad. It looks like poor implementation of configuration handling. Why do we need to specify servers list twice? 

The current implementation of `tfw_sched_http` uses groups of servers, while the core tempesta module doesn't know anything about groups. If you nest a "backend" within a "backend_group" in the configuration file, the main Tempesta FW module will never know about it. So if you load the module, you also have to specify which (already defined) server belong to which group. I don't see any way to avoid that without adding server groups to the core tempesta module.

> Well, both the schedulers schedule requests. So do we have duplicate logic? This is just an occasion that two algorithms do something similar things. If one of them is just a superset of other one, then it's Ok to merge them to single module. You already did it in failover branch and this is again just an implementation details - there is nothing about general scheduling infrastructure.

Yes, the `tfw_sched_http` is a superset of `tfw_sched_rr`. I suggested to not merge these schedulers, but to extract most of the `tfw_sched_http` to the main Tempesta FW module. If you take out server groups and URI/Host rules (see #76) out of the `tfw_sched_http`, then there will be nothing left there except the round-robin logic, and basically you get a duplicate of `tfw_sched_rr`.

**Comment by krizhanovsky** [comment]
> In other words, the sched_rr is able to make "bursts" of N requests to the same server, where N is the number of connections.

This is other bug in the implementation. Please fix.

> sched_http uses the hash value to choose a connection. That means that you can route requets with the same URI/Host not just to the same server, but also to the same connection within the server.

Yes. Schedulers in the new design will return TfwConnection instead of TfwServer, so the feature must be implemented in this way.

> The current implementation of tfw_sched_http uses groups of servers, while the core tempesta module doesn't know anything about groups. If you nest a "backend" within a "backend_group" in the configuration file, the main Tempesta FW module will never know about it. So if you load the module, you also have to specify which (already defined) server belong to which group. I don't see any way to avoid that without adding server groups to the core tempesta module.

Got it. This must be fixed in architecture redesign and in the schedulers implementation.

> Yes, the tfw_sched_http is a superset of tfw_sched_rr. I suggested to not merge these schedulers, but to extract most of the tfw_sched_http to the main Tempesta FW module.

Ok, agreed. I'll rework scheduling interfaces. However, not all the logic can be and/or should be in the main module. If you'll find some common logic between the schedulers, then you should just create some common .c or .h file with all necessary logic and use it in both the schedulers.

**Comment by krizhanovsky** [comment]
Comment https://github.com/natsys/tempesta/issues/78#issuecomment-84962898 is fixed in commit https://github.com/natsys/tempesta/commit/30f0e6dd24cd910a95d6624876df235a85e683eb: now we choose server using parsed HTTP request (https://github.com/natsys/tempesta/blob/master/tempesta_fw/http.c#L808)

**Comment by krizhanovsky** [comment]
I pushed the changes to ```iss78``` branch. Now schedulers are completely broken: sending HTTP request to Tempesta leads to 

        [tempesta] ERROR: No server group scheduler
        [tempesta] ERROR: Can't get an appropriate server connection for a session
        [sync_socket] Warning: can't process app data on socket ffff88007bf1e880
        [sync_socket]   Close socket ffff88007bf1e880 (account=1)

Now we have server groups with assigned schedulers as Dmitry proposed. However, before we scheduler a message among servers in a group we should choose which group we should use. And this is also a job for a scheduler. The common way to use server groups is to allocate them for different site resources, i.e. by URL. Thus HTTP scheduler must always be presented in the system (now we also support many schedulers) and choose the right server group.

Dmitry, I'm reassigning the issue to you since the schedulers are in your place. Please see ```FIXME #85``` comments firstly.
