### ISSUE TITLE
Configuration: configure protocol for listening sockets

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#82]
cfg.h has a good example of listening socket configuration:

        listen :443 [::0]:443 proto=https;

However, ```proto``` token is not parsed now. The feature must be implemented for ```http``` and ```https``` protocols. ```sock_clnt.c``` (previous ```sock_frontend.c```) must be updated accordingly.

See ```#82``` comments in the code.

Currently I'm updating the whole connections/sessions infrastructure, so the issue depends on #23 and #52. Also #81 depends on it.

**Comment by krizhanovsky** [comment]
Also please replace all ```backend``` in configuration by ```server```.

**Comment by stefanstrogin** [comment]
I'm sorry but as I see in https://github.com/natsys/tempesta/blob/master/tempesta_fw/cfg.c#L670 the token is actually parsed, an attribute with the key "proto" is added. If I'm not mistaken we should only handle this attribute in tfw_sock_clnt_cfg_handle_listen().

**Comment by stefanstrogin** [comment]
Fixed with https://github.com/natsys/tempesta/commit/216ed5d68787ed41b25a73fd4f06c7d0a37b6941
