### ISSUE TITLE
Tempesta, SKBs, and MSS

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#93]
Tempesta deals with SKBs that carry TCP stream with HTTP payload. While processing HTTP messages, Tempesta may change HTTP messages, or create and inject new HTTP messages. Ultimately, all traffic is packed in TCP packets and SKBs with total size no larger than MSS. It's necessary to understand the implications of that on how we work with SKBs in Tempesta. Below are the cases that exist in Tempesta.

* An SKB is taken from a receive socket, where it came to on one interface, and placed to a send socket, where it may go out on another interface. What if MSS of the egress interface is smaller?
* Tempesta may insert additional HTTP header fields into an HTTP message. Examples are `X-Forwarded-For:`, or `Set-Cookie:`. That may cause the total packet size to exceed MSS of the egress interface. Same is true when Tempesta updates an existing HTTP header field by adding some data to it.
* Tempesta may generate HTTP messages. For instance, HTTP error messages such as HTTP 502, or an HTTP 302 redirect message. Total size of these message should not exceed MSS as well.
* Tempesta may cache HTTP messages, and respond with a cached HTTP message. To do that, it builds SKBs with the HTTP message. That should also not exceed MSS.

There's an opinion that GSO will take care of that. But that needs further research and a conclusive answer.

**Comment by krizhanovsky** [comment]
It seems tso_fragment() called from tcp_write_xmit() is responsible for TCP egress fragmentation.
