### ISSUE TITLE
HTTP parser: Invalid length on some RAW header fields

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#94]
There is no specific test for this. You need to see the length of a full header field after Tempesta has parsed an HTTP message, and compare it to actual correct length. One of affected header fields is `Cookie:`, but there may be others.

When parsing a message, Tempesta HTTP parser checks for prefixes of "known' headers. The parser has separate specific states for that, states for specific prefixes. When that fails, the parser jumps to `HdrOther` state. The characters that were checked/skipped in those special states are not counted in total length in HdrOther state, hence the bug. Total length of the headers gets shorter by those few characters checked/skipped in special states. In case of `Cookie:` header field the magic number is 3 (characters that are not counted).

Everything is fine when parser goes directly to HdrOther state.

The fix to this is not obvious or straightforward. There's high probability that this bug is fixed in cc1c865880 that is not merged yet.

**Comment by krizhanovsky** [comment]
Commit https://github.com/natsys/tempesta/commit/562fc7acf99395f83dbd293a07a08fd1a353dbc8#diff-c8ebbbd47ae0c6f2c920761387bafab5R120 refers to the issue.
