### ISSUE TITLE
Kernel is polluted by stray Tempesta SKBs

### ISSUE THREAD

**Issue by keshonok** [natsys/tempesta#96]
This came up in research to find the core reason for #60 (Broken socket accounting). It turns out that SBKs that are in Tempesta's possession can be cloned by kernel on egress path. Cloned SKBs have their SKB header grossly inherited from the parent, and that includes the CB part that has Tempesta linked list pointers. These are the pointers that don't let the kernel delete SKBs that are still in Tempesta's possesssion. The check for that in implemented in `__kfree_skb()`. Now, Tempesta doesn't know anything about those cloned SKBs, and the kernel can't delete them now and ever due to that check. A system running Tempesta gets polluted by these stray SKBs that can't be deleted.

**Comment by krizhanovsky** [comment]
I merged your patch, should we close the issue?
Please do this if so.

**Comment by keshonok** [comment]
Fixed in 4468636
