### ISSUE TITLE
Update linux-3.10.10.patch

### ISSUE THREAD

**Issue by krizhanovsky** [natsys/tempesta#97]
I merged your patch for get_proto_family(), please update linux-3.10.10.patch appropriately.

**Comment by keshonok** [comment]
The new patch was merged to master (commits 5f835a7, b8652a6)
#87 requires another kernel patch, so I leave this open until that patch is merged.

**Comment by krizhanovsky** [comment]
Updated https://github.com/natsys/tempesta/commit/159e81c563cd301cfe7780f141dd23e467af182d
